routes/projects.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify
from db import db
from models import TodoList, ScheduleEventList, BlogUser, BlogPost
from datetime import datetime, timedelta, time, timezone
from flask_login import LoginManager, login_user, logout_user, login_required, current_user
from werkzeug.security import generate_password_hash, check_password_hash
import requests
import os

projects_bp = Blueprint('projects', __name__, url_prefix='/projects')

RECAPTCHA_SECRET_KEY = os.environ.get('RECAPTCHA_SECRET_KEY')

@projects_bp.route('/projectOverview')
def projectOverview_page():
    return render_template('projects/projectOverview.html', active_page = 'projectOverview')

@projects_bp.route('/contact/verify-captcha', methods=['POST'])
def verify_captcha():
    try:
        data = request.get_json()
        token = data.get('recaptcha_token')
    except Exception:
        return jsonify({'success': False, 'error': 'Invalid JSON data'}), 400
    
    if not token:
        return jsonify({'success': False, 'error': 'No token provided'}), 400
    
    payload = {
        'secret': RECAPTCHA_SECRET_KEY,
        'response': token,
        'remoteip': request.remote_addr
    }

    try:
        response = requests.post('https://www.google.com/recaptcha/api/siteverify', data=payload)
        response.raise_for_status()
        result = response.json()
    except requests.exceptions.RequestException as e:
        print(f"Google API Request failed: {e}")
        return jsonify({'success': False, 'error': 'Google API communication failed'}), 500
    
    if result.get('success'):
        return jsonify({'success': True}), 200
    else:
        print(f"reCAPTCHA verification failed. Error codes: {result.get('error-codes')}")
        return jsonify({'success': False, 'error': 'reCAPTCHA failed'}), 200
    

@projects_bp.route('/taskManager', methods = ['POST', 'GET'])
def taskManager_page():
    if request.method == 'POST':
        task_content = request.form["content"]
        new_task = TodoList(content = task_content)

        try:
            db.session.add(new_task)
            db.session.commit()
            return redirect(url_for('projects.taskManager_page'))
        except:
            return "There was an issue adding your task"
        

    else:
        tasks = TodoList.query.order_by(TodoList.date_created).all()
        return render_template('projects/taskManager/taskManager.html', active_page = 'taskManager', tasks = tasks)
    
@projects_bp.route('/taskManager/delete/<int:id>')
def delete(id):
    task_to_delete = TodoList.query.get_or_404(id)

    try:
        db.session.delete(task_to_delete)
        db.session.commit()
        return redirect(url_for('projects.taskManager_page'))
    except:
        return 'There was a problem deleting that task'
    
@projects_bp.route('/taskManager/update/<int:id>', methods=['GET', 'POST'])
def update(id):
    task = TodoList.query.get_or_404(id)
    if request.method == 'POST':
        task.content = request.form['content']

        try:
            db.session.commit()
            return redirect(url_for('projects.taskManager_page'))
        except:
            return "There was an issue updating your task"
        
    else:
        return render_template('projects/taskManager/update.html', active_page = 'taskManager', task=task)
    
@projects_bp.route('/schedulingCalendar', methods = ['POST', 'GET'])
def schedulingCalendar_page():
    if request.method == 'POST':
        event_data = request.get_json()

        start_time = event_data.get('start_time')
        end_time = event_data.get('end_time')

        if not start_time and not end_time:
            is_all_day = True
            formatted_start_time = time(0, 0, 0)
            formatted_end_time = time(0, 0, 0)
        elif start_time and not end_time:
            is_all_day = False
            formatted_start_time = datetime.strptime(start_time, '%I:%M %p').time()
            formatted_end_time = time(23,59,59)
        else:
            is_all_day = False

            if start_time:
                formatted_start_time = datetime.strptime(start_time, '%I:%M %p').time()
            else:
                formatted_start_time = time(0, 0, 0)
            
            if end_time:
                formatted_end_time = datetime.strptime(end_time, '%I:%M %p').time()
            else:
                if start_time:
                    formatted_end_time = time(23,59,59)
                else:
                    formatted_end_time = time(0, 0, 0)
        
        start_date_obj = datetime.strptime(event_data.get('start_date'), '%Y-%m-%d').date()
        end_date_obj = datetime.strptime(event_data.get('end_date'), '%Y-%m-%d').date()


        new_event = ScheduleEventList(
            title = event_data.get('title'),
            start_date = start_date_obj,
            end_date = end_date_obj,
            start_time = formatted_start_time,
            end_time = formatted_end_time,
            all_day = is_all_day,
            description = event_data.get('description'),
            url = event_data.get('url'),
            color = event_data.get('color')
        )

        db.session.add(new_event)
        db.session.commit()

        return jsonify({'message': 'Event added successfully'}), 201

    else:
        return render_template('projects/schedulerproject/scheduler.html', active_page = 'schedulingCalendar')
    
@projects_bp.route('/schedulingCalendar/eventViewer', methods = ['GET'])
def eventViewer_Page():
    events = ScheduleEventList.query.all()
    return render_template('projects/schedulerproject/eventViewer.html', active_page = 'schedulingCalendar', events = events)
    
@projects_bp.route('/schedulingCalendar/events', methods = ['GET'])
def get_all_events():

    start_str = request.args.get('start')
    end_str = request.args.get('end')

    start_date = datetime.fromisoformat(start_str)
    end_date = datetime.fromisoformat(end_str)

    events = ScheduleEventList.query.filter(
        (ScheduleEventList.start_date >= start_date) &
        (ScheduleEventList.end_date <= end_date)
    ).all()

    events_list = []

    for event in events:

        formatted_start_time = time(0,0,0)
        formatted_end_time = time(0,0,0)

        if event.start_time:
            formatted_start_time = event.start_time
        if event.end_time:
            formatted_end_time = event.end_time

        if event.all_day:
            start_datetime_obj = datetime.combine(event.start_date, formatted_start_time)
            end_date_exclusive_for_calendar = event.end_date + timedelta(days=1)
            end_datetime_obj = datetime.combine(end_date_exclusive_for_calendar, formatted_end_time)
        else:
            start_datetime_obj = datetime.combine(event.start_date, formatted_start_time)
            end_datetime_obj = datetime.combine(event.end_date, formatted_end_time)

        

        event_dict = {
            'id': event.id,
            'title': event.title,
            'start': start_datetime_obj.isoformat(),
            'end': end_datetime_obj.isoformat(),
            'allDay': bool(event.all_day),
            'url': event.url,
            'color': event.color,
            'extendedProps':{
                'description': event.description
            }
        }
        events_list.append(event_dict)

    return jsonify(events_list)

@projects_bp.route('/schedulingCalendar/update-event/<int:event_id>', methods = ['PUT'])
def update_event(event_id):
    event = ScheduleEventList.query.get(event_id)
    if not event:
        return jsonify({'error': 'Event not found'}), 404
    
    data = request.get_json()
    if not data:
        return jsonify({'error': 'Invalid data'}), 400
    
    event.title = data.get('title', event.title)
    event.description = data.get('description', event.description)
    event.color = data.get('color', event.color)

    if data.get('start_date'):
        pythonStartDate = datetime.strptime((data.get('start_date')), '%Y-%m-%d').date()
    else:
        pythonStartDate = event.start_date

    if data.get('end_date'):
        if event.all_day:
            pythonEndDate = datetime.strptime((data.get('end_date')), '%Y-%m-%d').date() - timedelta(days=1)
        else:
            pythonEndDate = datetime.strptime((data.get('end_date')), '%Y-%m-%d').date()
    else:
        pythonEndDate = event.end_date
    
    event.start_date = pythonStartDate
    event.end_date = pythonEndDate

    db.session.commit()

    return jsonify({'message': 'Event updated successfully'})

@projects_bp.route('/schedulingCalendar/delete-event/<int:event_id>', methods = ['DELETE'])
def delete_event(event_id):
    event = ScheduleEventList.query.get(event_id)
    if not event:
        return jsonify({'error': 'Event not found'}), 404
    
    db.session.delete(event)
    db.session.commit()

    return jsonify({'message': 'Event deleted successfully'})

@projects_bp.route('/schedulingCalendar/calendar-drag-event/<int:event_id>', methods = ['POST'])
def calendar_drag_event(event_id):
    event = ScheduleEventList.query.get(event_id)
    if not event:
        return jsonify({'error': 'Event not found'}), 404
    
    data = request.get_json()
    if not data:
        return jsonify({'error': 'Invalid data'}), 400

    if event.all_day:
        durationInHours = data.get('event_duration_hours')
        pythonStartDate = datetime.strptime((data.get('start_date')), '%Y-%m-%dT%H:%M:%S.%fZ').date()
        if durationInHours > 24:
            duration = timedelta(hours=durationInHours)
            pythonEndDate = pythonStartDate + duration - timedelta(days=1)

            event.start_date = pythonStartDate
            event.end_date = pythonEndDate
        else:
            event.start_date = pythonStartDate
            event.end_date = pythonStartDate
    else:
        pythonStartDate = datetime.strptime((data.get('start_date')), '%Y-%m-%dT%H:%M:%S.%fZ')

templates/projects/taskManager/taskManager.html
{% extends "base.html" %}

{% block title %}Task Manager{% endblock %}

{% block content %}
    <div class='py-3 bg-light'>
        <h1 class="text-center">Task Manager</h1>
    </div>
    <div class="container mt-4">
		<div class="text-center">
			<h1 class="mb-4">Task List</h1>
        	<h2 class="mb-3">Tasks</h2>
		</div>
        
        {% if tasks|length < 1 %}
        <h4 class="text-center">There are no tasks. Create one below!</h4>

        {% else %}
        <div class="table-responsive">
            <table class="table table-striped table-hover text-center">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Task</th>
                        <th scope="col">Added</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for task in tasks %}
                        <tr>
                            <td>{{ task.content }}</td>
                            <td>{{ task.date_created.date() }}</td>
                            <td>
                                <a href="{{ url_for('projects.delete', id=task.id) }}" class="btn btn-danger btn-sm">Delete</a>
                                <a href="{{ url_for('projects.update', id=task.id) }}" class="btn btn-info btn-sm">Update</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% endif %}

        <form action="{{ url_for('projects.taskManager_page') }}" method="POST" class="mt-4">
            <div class="form-group mb-3">
                <label for="content">Task:</label>
                <input type="text" id="content" name="content" class="form-control" placeholder="Enter new task...">
            </div>
            <button type="submit" class="btn btn-primary">Add Task</button>
        </form>
    </div>
{% endblock %}

templates/projects/taskManager/update.html
{% extends "base.html" %}

{% block title %}Update Task{% endblock %}

{% block content %}
    <div class='py-3 bg-light'>
        <h1 class="text-center">Update Task</h1>
    </div>
    <div class="container mt-4">

        <form action="{{ url_for('projects.update', id=task.id) }}" method="POST" class="mt-4">
            <div class="form-group mb-3">
                <label for="content">Task:</label>
                <input type="text" id="content" name="content" class="form-control" value="{{task.content}}">
            </div>
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
{% endblock %}